# Site settings
title: Christopher Rathjen's Profile
email: corbomite@theimprovisedstartrek.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to me.
baseurl: "/patchwork-gh-pages-24"
url: "http://rathjenc.github.io"
twitter_username: classicrathjen
github_username:  rathjenc
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
