# Site settings
title: Christopher Rathjen's Profile
email: chris.rathjen@GitHub.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "http://rathjenc.github.io/"
url: "http://rathjenc.github.io/"
twitter_username: classicrathjen
github_username:  rathjenc
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
